### ISSUE TITLE
Unusual use of hyphens in the text.

### ISSUE THREAD

**Issue by avinal** [RohitKaushal7/tpo-nith#1]
![image](https://user-images.githubusercontent.com/42297946/89128414-039df580-d513-11ea-981e-83795fd6d15a.png)
As you can see there are unusually placed hyphens in lots of **unhyphenable** (don't know if that's a word even) words. 
* orga-nization
* peace-ful
* Com-puter
* learn-ing
* com-mitted
* re-cruiting and lot many. They are everywhere 😅

If it is a coding issue then close the issue or something that can be corrected with little modification. Or I am happy to work on this. @RohitKaushal7

**Comment by RohitKaushal7** [comment]
@avinal  Feel free to correct these and any other grammatical mistakes if you find any. Thanks :heart: .

**Comment by RohitKaushal7** [comment]
Closing wrt PR #3
